language: node_js
node_js:
  - "6"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
  - npm install
  - npm install -g gulp-cli
script: gulp test
env:
  - VUE_VERSION=2.0.0
  - VUE_VERSION=2.1.0
  - VUE_VERSION=2.2.0
  - VUE_VERSION=2.3.0
  - VUE_VERSION=2.4.0
